dist: bionic
sudo: required
cache:
  pip: true
stages:
  - test
  - name: deploy
    if: repo = faucetsdn/beka AND tag IS present
script:
  - ./travis/runtests.sh
jobs:
  include:
    - stage: test
      language: python
      python: 3.5
      env:
        - TRAVIS_SHARD=unittest
    - stage: test
      language: python
      python: 3.6
      env:
        - TRAVIS_SHARD=unittest
        - CODE_CHECK=true
        - CODE_COV=true
    - stage: test
      language: python
      python: 3.7
      env: TRAVIS_SHARD=unittest
    - stage: deploy
      language: python
      python: 3.6
      install: skip
      before_script: skip
      script: skip
      after_script: skip
      deploy:
        provider: pypi
        on:
          tags: true
        user: __token__
        password:
          secure: rVLAd9p7MQRginQThVuIGpmaMG8G71NPZVxu675owNUR2nPkXzjO0LGyXDmtZdZalV4IylX0YZCRQHKbzYoUIP/AUffZZJTfHxCUUa6X1xTyTdjPD6Wi5ZhO0RXoIDLuUZNZh4TKN8b7DKU/krm3it8C/JLG7yjCMxBXmkcuPpyTMFEB7VMlpKsbxIjXH2vqtpK/ILrtQt82MbPn5wE2HUrJb+ZB0WDq0jm8UBOBvUgFzVGjpM/cwyHxBrr83DPN7+Ky9o/MDMtzB8ztUFgU50FgsXKMSfKdoyM+DZ06S8IW/mlDqLTKCvd/ntlguj467s4P1TjkzwiOlfzINa4BZ/RKVbCk0G0dJY/8Jc42dsRB1pmXeyTpc9lfqDsGVPdwZ4+Rbehm0C9aWDLrGkEkGUgtcJOyrSmDsQcNobVYnVQ/39syNFHvrKtC6o0aP90rL1TSrpgu1iXtPQhXLd0bVmSnDxDizhUSZkTIdptCIWAxlw7mMWW50ixImRHqNuW/g758vsvefgyT5lhgExv6NVleyxYoxP6kzCA1Ge3O1/hmAkX9s3qAnEoiqHxlPJbKT9HfLzUa78XP56vxQ6zQ0hXc8NzV+hRN8W3xv206wroNYa/UrGzYGLjT/X0qq9o9V0MJhxRPGfv6KTli+oTKTcj3he4qSM2stLWSlcu6kVg=
